import Head from "next/head";

import { homeDoc } from "../constants/documentTitle";
import { PreviewSuspense } from "next-sanity/preview";
import { lazy } from "react";
import { client } from "../lib/sanity.client";
import {
  AuthorDocument,
  AuthorQuery,
} from "../components/Document/Author/AuthorDocument";

const PreviewDocumentsCount = lazy(
  () => import("../components/Document/PreviewDocumentsCount")
);

export const getStaticProps = async ({ preview = false }) => {
  if (preview) {
    return { props: { preview } };
  }

  const data = await client.fetch(AuthorQuery);

  return { props: { preview, data } };
};

export default function Home({ preview, data }: any) {
  if (preview) {
    return (
      <PreviewSuspense fallback="Loading...">
        <PreviewDocumentsCount />
      </PreviewSuspense>
    );
  }
  return (
    <>
      <Head>
        <title>{homeDoc}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthorDocument data={data} />
    </>
  );
}
